# Generated by CogSol 0.2.0 on 2026-02-22 09:20
from cogsol.db import migrations


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateTopic(name='flights', fields={'name': 'flights'}, meta={'description': 'Flight routes, schedules, and pricing information'}),
        migrations.CreateTopic(name='hotels', fields={'name': 'hotels'}, meta={'description': 'Hotel accommodations, locations, and corporate rates'}),
        migrations.CreateTopic(name='policies', fields={'name': 'policies'}, meta={'description': 'Corporate travel expense policies and approval rules'}),
        migrations.CreateReferenceFormatter(name='orchestrator_formatter', fields={'name': 'orchestrator_formatter', 'description': 'Reference format for travel planning documents.', 'expression': '[{name}]'}),
        migrations.CreateIngestionConfig(name='orchestrator_ingestion', fields={'name': 'orchestrator_ingestion', 'pdf_parsing_mode': 'manual', 'chunking_mode': 'langchain', 'max_size_block': 2500, 'chunk_overlap': 100, 'separators': [], 'ocr': False, 'additional_prompt_instructions': '', 'assign_paths_as_metadata': False}),
        migrations.CreateRetrieval(name='orchestrator_flights', fields={'name': 'orchestrator_flights', 'num_refs': 5, 'max_msg_length': 570, 'reordering': False, 'strategy_reordering': None, 'previous_blocks': 1, 'next_blocks': 1, 'contingency_for_embedding': True, 'threshold_similarity': 0.7, 'formatters': {'Markdown': 'orchestrator_formatter'}, 'filters': [], 'topic': 'flights'}),
        migrations.CreateRetrieval(name='orchestrator_hotels', fields={'name': 'orchestrator_hotels', 'num_refs': 5, 'max_msg_length': 570, 'reordering': False, 'strategy_reordering': None, 'previous_blocks': 1, 'next_blocks': 1, 'contingency_for_embedding': True, 'threshold_similarity': 0.7, 'formatters': {'Markdown': 'orchestrator_formatter'}, 'filters': [], 'topic': 'hotels'}),
        migrations.CreateRetrieval(name='orchestrator_policies', fields={'name': 'orchestrator_policies', 'num_refs': 5, 'max_msg_length': 570, 'reordering': False, 'strategy_reordering': None, 'previous_blocks': 1, 'next_blocks': 1, 'contingency_for_embedding': True, 'threshold_similarity': 0.7, 'formatters': {'Markdown': 'orchestrator_formatter'}, 'filters': [], 'topic': 'policies'}),
    ]
