# Generated by CogSol 0.2.0 on 2026-02-12 14:32
from cogsol.db import migrations


class Migration(migrations.Migration):
    initial = False
    dependencies = [('agents', '0004_auto_20260212_1430')]
    operations = [
        migrations.AlterField(model_name='PretoolsAgent', name='pregeneration_config', value='QA', entity='agents', scope='fields'),
    ]
