# Generated by CogSol 0.2.0 on 2026-02-12 14:33
from cogsol.db import migrations


class Migration(migrations.Migration):
    initial = False
    dependencies = [('agents', '0005_auto_20260212_1432')]
    operations = [
        migrations.AlterField(model_name='PretoolsAgent', name='tools', value=['current_datetime', 'weather_info', 'daily_tip'], entity='agents', scope='fields'),
    ]
