# Generated by CogSol 0.2.0 on 2026-03-11 12:00
from cogsol.db import migrations


class Migration(migrations.Migration):
    initial = False
    dependencies = ["0001_initial"]
    operations = [
        migrations.AlterField(
            model_name='HelpDeskSearch',
            name='retrieval',
            value='helpdesk_search',
            entity='retrieval_tools',
        ),
        migrations.AlterField(
            model_name='HelpDeskSearch',
            name='description',
            value='Search the IT knowledge base for troubleshooting guides, policies, and how-to articles. Optionally filter by category.',
            entity='retrieval_tools',
        ),
        migrations.AlterField(
            model_name='HelpDeskSearch',
            name='parameters',
            value=[
                {
                    'name': 'question',
                    'description': 'Search query describing the issue or topic',
                    'type': 'string',
                    'required': True,
                },
                {
                    'name': 'category',
                    'description': 'Filter by article category: Network, Hardware, Software, Security, or Onboarding',
                    'type': 'string',
                    'required': False,
                },
            ],
            entity='retrieval_tools',
        ),
    ]
