# Generated by CogSol 0.2.0 on 2026-02-13 16:04
from cogsol.db import migrations


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateRetrievalTool(name='MovieSearch', fields={'description': 'Search movies by plot, theme, or any description. Optionally filter by genre, language, or decade.', 'parameters': [{'description': 'Search query describing the movie', 'name': 'question', 'required': True, 'type': 'string'}, {'description': 'Filter by movie genre', 'name': 'genre', 'required': False, 'type': 'string'}, {'description': 'Filter by original language', 'name': 'language', 'required': False, 'type': 'string'}, {'description': 'Filter by decade of release', 'name': 'decade', 'required': False, 'type': 'string'}], 'name': 'MovieSearch'}),
        migrations.CreateAgent(name='MovieSearchAgent', fields={'system_prompt': '# Movie Search Assistant\n\nYou are a helpful assistant that finds movies based on user queries.', 'generation_config': 'QA', 'temperature': 0.3, 'max_responses': 10, 'max_msg_length': 2048, 'max_consecutive_tool_calls': 3, 'tools': ['MovieSearch'], 'initial_message': "Hello! I am the Movie Search Assistant. I can help you find movies by describing what you are looking for. You can also narrow results by genre, language, or decade. Try asking me something like 'a suspenseful movie set in space' or 'a French comedy from the 2000s'.", 'forced_termination_message': 'We are ending this conversation to preserve security and integrity.', 'no_information_message': 'I could not find a matching movie for that query. Try rephrasing your request or adjusting the filters.', 'name': 'MovieSearch'}, meta={'name': 'MovieSearchAgent', 'chat_name': 'Movie Search Assistant'}),
    ]
