# Generated by CogSol 0.2.0 on 2026-02-13 16:04
from cogsol.db import migrations


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateTopic(name='movies', fields={'name': 'movies'}, meta={'description': 'Collection of movie synopses for semantic search with filters'}),
        migrations.CreateReferenceFormatter(name='movie_formatter', fields={'name': 'movie_formatter', 'description': 'Reference format for movie documents.', 'expression': '[{name}]'}),
        migrations.CreateIngestionConfig(name='movie_ingestion', fields={'name': 'movie_ingestion', 'pdf_parsing_mode': 'manual', 'chunking_mode': 'langchain', 'max_size_block': 2500, 'chunk_overlap': 100, 'separators': [], 'ocr': False, 'additional_prompt_instructions': '', 'assign_paths_as_metadata': False}),
        migrations.CreateRetrieval(name='movie_search', fields={'name': 'movie_search', 'num_refs': 5, 'max_msg_length': 570, 'reordering': False, 'strategy_reordering': None, 'previous_blocks': 1, 'next_blocks': 1, 'contingency_for_embedding': True, 'threshold_similarity': 0.7, 'formatters': {'Markdown': 'movie_formatter'}, 'filters': ["<class 'data.movies.metadata.GenreMetadata'>", "<class 'data.movies.metadata.LanguageMetadata'>", "<class 'data.movies.metadata.DecadeMetadata'>"], 'topic': 'movies'}),
        migrations.CreateMetadataConfig(name='movies/decade', fields={'name': 'decade', 'type': 'STRING', 'possible_values': ['1990s', '2000s', '2010s', '2020s'], 'filtrable': True, 'required': False, 'in_retrieval': True}, topic='movies'),
        migrations.CreateMetadataConfig(name='movies/genre', fields={'name': 'genre', 'type': 'STRING', 'possible_values': ['Action', 'Comedy', 'Drama', 'Horror', 'Sci-Fi', 'Romance', 'Thriller', 'Animation'], 'filtrable': True, 'required': False, 'in_retrieval': True}, topic='movies'),
        migrations.CreateMetadataConfig(name='movies/language', fields={'name': 'language', 'type': 'STRING', 'possible_values': ['English', 'Spanish', 'French', 'Japanese', 'Korean'], 'filtrable': True, 'required': False, 'in_retrieval': True}, topic='movies'),
    ]
