# Generated by CogSol 0.2.0 on 2026-02-20 12:00
from cogsol.db import migrations


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateTopic(name='documents', fields={'name': 'documents'}, meta={'description': 'Document collection for semantic search'}),
        migrations.CreateReferenceFormatter(name='document_formatter', fields={'name': 'document_formatter', 'description': 'Reference format for documents.', 'expression': '[{name}]'}),
        migrations.CreateIngestionConfig(name='document_ingestion', fields={'name': 'document_ingestion', 'pdf_parsing_mode': 'manual', 'chunking_mode': 'langchain', 'max_size_block': 2500, 'chunk_overlap': 100, 'separators': [], 'ocr': False, 'additional_prompt_instructions': '', 'assign_paths_as_metadata': False}),
        migrations.CreateRetrieval(name='document_search', fields={'name': 'document_search', 'num_refs': 5, 'max_msg_length': 570, 'reordering': False, 'strategy_reordering': None, 'previous_blocks': 1, 'next_blocks': 1, 'contingency_for_embedding': True, 'threshold_similarity': 0.7, 'formatters': {'Markdown': 'document_formatter'}, 'filters': [], 'topic': 'documents'}),
    ]
