# Generated by CogSol 0.2.0 on 2026-02-20 12:00
from cogsol.db import migrations


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateRetrievalTool(name='SemanticSearch', fields={'description': 'Semantic search over the document collection.', 'parameters': [], 'name': 'SemanticSearch'}),
        migrations.CreateAgent(name='SemanticSearchAgent', fields={'system_prompt': '# Semantic Search Assistant\n\nYou are a helpful assistant that finds relevant information based on user queries.', 'generation_config': 'QA', 'temperature': 0.3, 'max_responses': 10, 'max_msg_length': 2048, 'max_consecutive_tool_calls': 3, 'tools': ['SemanticSearch'], 'initial_message': 'Hello! I can help you find information in the knowledge base. Describe what you are looking for and I will search for you.', 'forced_termination_message': 'Thank you for using the Semantic Search Assistant. Visit https://docs.cogsol.ai for the full reference.', 'no_information_message': 'I could not find relevant results for that query. Try rephrasing your request or using different keywords.', 'name': 'SemanticSearch'}, meta={'name': 'SemanticSearchAgent', 'chat_name': 'Semantic Search Assistant'}),
    ]
