# Generated by CogSol 0.2.0 on 2026-02-13 15:31
from cogsol.db import migrations


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateRetrievalTool(name='RecipeSearch', fields={'description': 'Search recipes by ingredients, cuisine, dish type, or any food-related query.', 'parameters': [], 'name': 'RecipeSearch'}),
        migrations.CreateAgent(name='RecipeSearchAgent', fields={'system_prompt': '# Recipe Search Assistant\n\nYou are a helpful assistant that finds recipes based on user queries.', 'generation_config': 'QA', 'temperature': 0.3, 'max_responses': 10, 'max_msg_length': 2048, 'max_consecutive_tool_calls': 3, 'tools': ['RecipeSearch'], 'initial_message': "Hello! I am the Recipe Search Assistant. I can help you find recipes by ingredients, cuisine type, or any description of what you are in the mood for. Try asking me something like 'something light with chicken' or 'an easy chocolate dessert'.", 'forced_termination_message': 'Thank you for using the Recipe Search Assistant. Visit https://docs.cogsol.ai for the full reference.', 'no_information_message': 'I could not find a matching recipe for that query. Try rephrasing your request or using different keywords.', 'name': 'RecipeSearchAgent'}, meta={'name': 'RecipeSearchAgent', 'chat_name': 'Recipe Search Assistant'}),
    ]
