# Generated by CogSol 0.2.0 on 2026-02-28 09:47
from cogsol.db import migrations


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateTopic(name='knowledgebase', fields={'name': 'knowledgebase'}, meta={'description': 'IT help desk knowledge base articles'}),
        migrations.CreateReferenceFormatter(name='helpdesk_formatter', fields={'name': 'helpdesk_formatter', 'description': 'Reference format for IT knowledge base articles.', 'expression': '[{name}]'}),
        migrations.CreateIngestionConfig(name='helpdesk_ingestion', fields={'name': 'helpdesk_ingestion', 'pdf_parsing_mode': 'manual', 'chunking_mode': 'langchain', 'max_size_block': 2500, 'chunk_overlap': 100, 'separators': [], 'ocr': False, 'additional_prompt_instructions': '', 'assign_paths_as_metadata': False}),
        migrations.CreateRetrieval(name='helpdesk_search', fields={'name': 'helpdesk_search', 'num_refs': 5, 'max_msg_length': 570, 'reordering': False, 'strategy_reordering': None, 'previous_blocks': 1, 'next_blocks': 1, 'contingency_for_embedding': True, 'threshold_similarity': 0.7, 'formatters': {'Markdown': 'helpdesk_formatter'}, 'filters': [], 'topic': 'knowledgebase'}),
    ]
