# Generated by CogSol 0.2.0 on 2026-03-11 12:00
from cogsol.db import migrations


class Migration(migrations.Migration):
    initial = False
    dependencies = ["0001_initial"]
    operations = [
        migrations.CreateMetadataConfig(
            name='knowledgebase/category',
            fields={
                'name': 'category',
                'type': 'STRING',
                'possible_values': ['Network', 'Hardware', 'Software', 'Security', 'Onboarding'],
                'filtrable': True,
                'required': False,
                'in_retrieval': True,
            },
            topic='knowledgebase',
        ),
        migrations.AlterField(
            model_name='helpdesk_search',
            name='filters',
            value=["<class 'data.knowledgebase.metadata.CategoryMetadata'>"],
            entity='retrievals',
        ),
    ]
