# Generated by CogSol 0.2.0 on 2026-02-22 07:42
from cogsol.db import migrations


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateTopic(name='americas', fields={'name': 'americas'}, meta={'description': 'Travel destinations in the Americas'}),
        migrations.CreateTopic(name='asia', fields={'name': 'asia'}, meta={'description': 'Travel destinations in Asia'}),
        migrations.CreateTopic(name='europe', fields={'name': 'europe'}, meta={'description': 'Travel destinations in Europe'}),
        migrations.CreateReferenceFormatter(name='travel_formatter', fields={'name': 'travel_formatter', 'description': 'Reference format for travel destination documents.', 'expression': '[{name}]'}),
        migrations.CreateIngestionConfig(name='travel_ingestion', fields={'name': 'travel_ingestion', 'pdf_parsing_mode': 'manual', 'chunking_mode': 'langchain', 'max_size_block': 2500, 'chunk_overlap': 100, 'separators': [], 'ocr': False, 'additional_prompt_instructions': '', 'assign_paths_as_metadata': False}),
        migrations.CreateRetrieval(name='search_selector_americas', fields={'name': 'search_selector_americas', 'num_refs': 5, 'max_msg_length': 570, 'reordering': False, 'strategy_reordering': None, 'previous_blocks': 1, 'next_blocks': 1, 'contingency_for_embedding': True, 'threshold_similarity': 0.7, 'formatters': {'Markdown': 'travel_formatter'}, 'filters': [], 'topic': 'americas'}),
        migrations.CreateRetrieval(name='search_selector_asia', fields={'name': 'search_selector_asia', 'num_refs': 5, 'max_msg_length': 570, 'reordering': False, 'strategy_reordering': None, 'previous_blocks': 1, 'next_blocks': 1, 'contingency_for_embedding': True, 'threshold_similarity': 0.7, 'formatters': {'Markdown': 'travel_formatter'}, 'filters': [], 'topic': 'asia'}),
        migrations.CreateRetrieval(name='search_selector_europe', fields={'name': 'search_selector_europe', 'num_refs': 5, 'max_msg_length': 570, 'reordering': False, 'strategy_reordering': None, 'previous_blocks': 1, 'next_blocks': 1, 'contingency_for_embedding': True, 'threshold_similarity': 0.7, 'formatters': {'Markdown': 'travel_formatter'}, 'filters': [], 'topic': 'europe'}),
    ]
